# Adding the shared folder to the pythonpath allows development work for the current repository
# given that the actual python app is located on the root, e.g., openwind/openwind
- name: openwind | Add PYTHONPATH to bashrc
  lineinfile: dest="/home/vagrant/.bashrc" line="export PYTHONPATH=/vagrant"

  #- name: openwind | Update/checkout Nansat
  #  git: repo=https://github.com/nansencenter/nansat
  #       dest="{{ dev_sources_dir }}/nansat/"
  #       version="{{ nansat_version }}"
  #       update=yes
  #  register: git_nansat
  #  tags:
  #    - update-nansat
  #  ignore_errors: no
  #
  #- name: openwind | Clean Nansat (always run to keep the pixel functions updated)
  #  shell: 'python setup.py clean --all'
  #  args:
  #    chdir: '{{ dev_sources_dir }}/nansat'
  #  tags:
  #    - update-nansat
  #
  #- name: openwind | Install Nansat (always run to keep the pixel functions updated)
  #  shell: 'python setup.py build_ext --inplace'
  #  args:
  #    chdir: '{{ dev_sources_dir }}/nansat'
  #  tags:
  #    - update-nansat
  #
  #- name: openwind | Create link from Python dist-packages to nansat
  #  file: path='{{ python_dist_packages }}/nansat'
  #        src='{{ dev_sources_dir }}/nansat/nansat'
  #        state=link
  #        force=yes
  #
  #- name: nansat | Create link from Python dist-packages to nansat_integration_tests
  #
