# Adding the shared folder to the pythonpath allows development work for the current repository
# given that the actual python app is located on the root, e.g., openwind/openwind
- name: openwind | Add PYTHONPATH to bashrc
  lineinfile: dest="/home/vagrant/.bashrc" line="export PYTHONPATH=/vagrant"

- name: openwind | Change owner of anaconda directory
  shell: 'sudo chown -R vagrant /home/vagrant/anaconda/'

- name: openwind | Add Jupyter Notebook to crontab
  cron: name="Jupyter Notebook" special_time=reboot job="sleep 60; {{ conda_dir }}/envs/{{ env_name }}/bin/jupyter-notebook --ip=0.0.0.0 --no-browser --notebook-dir=/vagrant/notebooks/ --NotebookApp.token=vagrant"

- name: openwind | Check if Jupyter is running
  shell: ps aux | grep jupyter | grep -v grep
  ignore_errors: yes
  changed_when: false
  register: jupyter_status

- name: openwind | Launch Jupyter Notebook
  shell: "nohup {{ conda_dir }}/envs/{{ env_name }}/bin/jupyter-notebook --ip=0.0.0.0 --no-browser --notebook-dir=/vagrant/notebooks/ --NotebookApp.token=vagrant > /dev/null 2>&1 &"
  when: jupyter_status.rc != 0

  #- name: Nansat Setup Python | Check if numpy is imported
  #  shell: "nosetests test_import.py"
  #  args:
  #    chdir: "{{ shared_dir }}"

  #- name: openwind | Update/checkout Nansat
  #  git: repo=https://github.com/nansencenter/nansat
  #       dest="{{ dev_sources_dir }}/nansat/"
  #       version="{{ nansat_version }}"
  #       update=yes
  #  register: git_nansat
  #  tags:
  #    - update-nansat
  #  ignore_errors: no
  #
  #- name: openwind | Clean Nansat (always run to keep the pixel functions updated)
  #  shell: 'python setup.py clean --all'
  #  args:
  #    chdir: '{{ dev_sources_dir }}/nansat'
  #  tags:
  #    - update-nansat
  #
  #- name: openwind | Install Nansat (always run to keep the pixel functions updated)
  #  shell: 'python setup.py build_ext --inplace'
  #  args:
  #    chdir: '{{ dev_sources_dir }}/nansat'
  #  tags:
  #    - update-nansat
  #
  #- name: openwind | Create link from Python dist-packages to nansat
  #  file: path='{{ python_dist_packages }}/nansat'
  #        src='{{ dev_sources_dir }}/nansat/nansat'
  #        state=link
  #        force=yes
  #
  #- name: nansat | Create link from Python dist-packages to nansat_integration_tests
  #
