---
channels:
  - conda-forge
dependencies:
  - python=3.6
  - scipy
  - django
  - binutils
  - pyproj
  - gdal=2.2
  - libspatialite
  - pythesint
  - nansat
  - nose
  - coveralls
  - mock
  - ipython
  - ipdb
  - thredds_crawler
  - cartopy
  - basemap-data-hires
  - folium
  - jupyter
